# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  linux:
    name: Deploy for Linux
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          sudo apt install libx11-dev libxtst-dev libwayland-dev libxkbcommon-dev
          npm install
      - name: Fix Permissions
        # Workaround for https://github.com/electron/electron/issues/17972
        run: |
          sudo chmod 4755 node_modules/electron/dist/chrome-sandbox
          sudo chown root node_modules/electron/dist/chrome-sandbox
      - name: Create Packages
        run: |
          npm run make
      - name: Create AppImage
        run: |
          tools/make-app-image.sh
      - name: Upload Packages
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/make/**/*
          tag: ${{ github.ref }}
          file_glob: true

  windows:
    name: Deploy for Windows
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        # For some reason cmake.js sometimes skips the build step in CI on Windows in this
        # case. So we install and execute cmake.js manually.
        run: |
          npm install cmake-js -g
          npx cmake-js install
          npm install
      - name: Create Release
        run: |
          npm run make
      - name: Upload Zip
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/make/zip/win32/x64/*
          tag: ${{ github.ref }}
          file_glob: true
      - name: Upload Squirrel Installer
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/make/squirrel.windows/x64/*.exe
          tag: ${{ github.ref }}
          file_glob: true

  macos:
    name: Deploy for macOS
    strategy:
      matrix:
        os: [macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      # https://github.com/electron/forge/issues/2807
      - run: python3 -m pip install setuptools --break-system-packages
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          npm install
          npm install appdmg
      - name: Add macOS certificates
        env:
          OSX_CERTIFICATE: ${{ secrets.OSX_CERTIFICATE }}
          OSX_CERTIFICATE_PASSWORD: ${{ secrets.OSX_CERTIFICATE_PASSWORD }}
        run: |
          .github/osx_certificates.sh
      - name: Create Release
        env:
          KANDO_OSX_SIGN: false
          KANDO_OSX_NOTARIZE: false
          OSX_APP_SPECIFIC_ID: ${{ secrets.OSX_APP_SPECIFIC_ID }}
          OSX_APP_SPECIFIC_PASSWORD: ${{ secrets.OSX_APP_SPECIFIC_PASSWORD }}
          OSX_TEAM_ID: ${{ secrets.OSX_TEAM_ID }}
        run: |
          npm run make
      - name: Upload DMG
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/make/*.dmg
          tag: ${{ github.ref }}
          file_glob: true
      - name: Upload Zip
        uses: svenstaro/upload-release-action@v2
        with:
          file: out/make/zip/darwin/**/*.zip
          tag: ${{ github.ref }}
          file_glob: true
